name: calendar_components
description: A collection of basic composable components for creating calendars.
version: 0.1.0
homepage: https://github.com/pongloongyeat/calendar_components

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
