name: calendar_components
description: A collection of basic composable components for creating calendars.
version: 0.0.1
homepage: https://github.com/pongloongyeat/calendar_components

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
